        // Productos con IDs únicos
        const productos = [
            { id: "id-7", nombre: "Arroz - Molinos Ala" },
            { id: "id-1", nombre: "Arroz Oro - Gallo" },
            { id: "id-9", nombre: "Azucar - Domino" },
            { id: "id-18", nombre: "Azucar - F. Canella" },
            { id: "id-10", nombre: "Azucar - La Principal" },
            { id: "id-27", nombre: "Ayudin Cloro" },
            { id: "id-19", nombre: "Codito Lucchetti" },
            { id: "id-24", nombre: "Desinfectante CIF" },
            { id: "id-25", nombre: "Desinfectante Lysoform" },
            { id: "id-26", nombre: "Detergente EXPERT CIF" },
            { id: "id-23", nombre: "Detergente CIF" },
            { id: "id-17", nombre: "Fideo Resorte Colores - Matarazzo" },
            { id: "id-2", nombre: "G. Agua - La Provinciana" },
            { id: "id-11", nombre: "Harina 000 - BlancaFlor" },
            { id: "id-4", nombre: "Kesitas" },
            { id: "id-8", nombre: "Lentejas" },
            { id: "id-15", nombre: "Limonada y Arandanos - Clight" },
            { id: "id-3", nombre: "Matecodico - Nobleza Gaucha" },
            { id: "id-13", nombre: "Naranja Banana - TANG" },
            { id: "id-16", nombre: "Papel de Cocina - Husuares" },
            { id: "id-20", nombre: "Penne Rigate Lucchetti" },
            { id: "id-14", nombre: "Pera - TANG" },
            { id: "id-22", nombre: "Servilleta Felpita" },
            { id: "id-21", nombre: "Tirabuzon Lucchetti"},
            { id: "id-12", nombre: "Tostada - Manieri" },
            { id: "id-6", nombre: "Yerba - Amanda" },
            { id: "id-5", nombre: "Yerba - Union" }
        ];

        // ID, nombre, marca, cantidad y vencimiento
        const stock = [
            { id: "id-7", nombre: "Arroz", marca: "Molinos Ala", cantidad: "8 x 1kg", vencimiento: "01/01/2026" },
            { id: "id-1", nombre: "Arroz Oro", marca: "Gallo", cantidad: "15 x 1kg", vencimiento: "NO ENCONTRADA" },
            { id: "id-9", nombre: "Azucar", marca: "Domino", cantidad: "20 x 1kg", vencimiento: "NO TIENE" },
            { id: "id-18", nombre: "Azucar", marca: "F. Canella", cantidad: "20 x 1kg", vencimiento: "NO TIENE" },
            { id: "id-10", nombre: "Azucar", marca: "La Principal", cantidad: "0 x 1kg", vencimiento: "NO TIENE" },
            { id: "id-27", nombre: "Cloro", marca: "Ayudin", cantidad: "3 x 450ml", vencimiento: "NO TIENE" },
            { id: "id-19", nombre: "Fideo Codito", marca: "Lucchetti", cantidad: "4 x 500gr", vencimiento: "23/03/2027" },
            { id: "id-24", nombre: "Desinfectante", marca: "CIF", cantidad: "2 x 380ml", vencimiento: "NO TIENE" },
            { id: "id-25", nombre: "Desinfectante", marca: "Lysoform", cantidad: "3 x 490ml", vencimiento: "NO TIENE" },
            { id: "id-26", nombre: "Detergente EXPERT", marca: "CIF", cantidad: "1 x 450ml", vencimiento: "NO TIENE" },
            { id: "id-23", nombre: "Detergente", marca: "CIF", cantidad: "2 x 450ml", vencimiento: "NO TIENE" },
            { id: "id-17", nombre: "Fideo Resorte Colores", marca: "Matarazzo", cantidad: "0", vencimiento: "NO ENCONTRADA" },
            { id: "id-2", nombre: "G. de Agua", marca: "La Provinciana", cantidad: "14 x 3", vencimiento: "01/06/2025" },
            { id: "id-11", nombre: "Harina 000", marca: "Blanca Flor", cantidad: "6 x 1kg", vencimiento: "NO TIENE" },
            { id: "id-4", nombre: "Snack", marca: "Kesitas", cantidad: "7 x 125gr", vencimiento: "26/10/2025" },
            { id: "id-8", nombre: "Lentejas", marca: "No disponible", cantidad: "10 x 400gr", vencimiento: "NO TIENE" },
            { id: "id-15", nombre: "Sobre Limonada y Arandanos", marca: "Clight", cantidad: "6 x 20", vencimiento: "20/03/2026" },
            { id: "id-3", nombre: "Matecocido", marca: "Nobleza Gaucha", cantidad: "7 x 50", vencimiento: "NO TIENE" },
            { id: "id-13", nombre: "Sobre Naranja Banana", marca: "TANG", cantidad: "3 x 20", vencimiento: "28/02/2026" },
            { id: "id-16", nombre: "Papel de Cocina", marca: "Husuares", cantidad: "7 x 3", vencimiento: "NO TIENE" },
            { id: "id-20", nombre: "Fideos Penne Rigate", marca: "Lucchetti", cantidad: "2 x 500gr", vencimiento: "20/02/2027" },
            { id: "id-14", nombre: "Sobre Pera", marca: "TANG", cantidad: "1 x 19", vencimiento: "04/02/2026" },
            { id: "id-22", nombre: "Servilleta", marca: "Felpita", cantidad: "2 x 70", vencimiento: "NO TIENE" },
            { id: "id-21", nombre: "Fideos Tirabuzon", marca: "Lucchetti", cantidad: "3 x 500gr", vencimiento: "08/03/2027" },
            { id: "id-12", nombre: "G. Tostada", marca: "Manieri", cantidad: "4 x 200gr", vencimiento: "NO ENCONTRADO" },
            { id: "id-6", nombre: "Yerba", marca: "Amanda", cantidad: "7 x 500gr", vencimiento: "NO TIENE" },
            { id: "id-5", nombre: "Yerba", marca: "Union", cantidad: "26 x 500gr", vencimiento: "NO TIENE" }
        ]