        // Productos con IDs únicos
        const productos = [
            { id: "id-1", nombre: "Arroz Oro - Gallo" },
            { id: "id-2", nombre: "G. de Agua - La Provinciana" },
            { id: "id-19", nombre: "Fideo Codito - Lucchetti" },
            { id: "id-17", nombre: "Fideo Resorte Colores - Matarazzo" },
            { id: "id-4", nombre: "Snack - Kesitas" },
            { id: "id-8", nombre: "Lentejas - Alberio" },
            { id: "id-20", nombre: "Fideos Tubitos - Lucchetti" },
            { id: "id-21", nombre: "Fideos Tirabuzon - Lucchetti" },
            { id: "id-9", nombre: "Azucar - Domino" },
            { id: "id-18", nombre: "Azucar - F. Canella" },
            { id: "id-27", nombre: "Cloro - Ayudin" },
            { id: "id-24", nombre: "Desinfectante - CIF" },
            { id: "id-25", nombre: "Desinfectante - Lysoform" },
            { id: "id-26", nombre: "Detergente EXPERT - CIF" },
            { id: "id-23", nombre: "Detergente - CIF" },
            { id: "id-15", nombre: "Sobre Limonada y Arandanos - Clight" },
            { id: "id-13", nombre: "Sobre Naranja Banana - TANG" },
            { id: "id-14", nombre: "Sobre Pera - TANG" },
            { id: "id-3", nombre: "Mate cocido - Nobleza Gaucha" },
            { id: "id-22", nombre: "Servilleta - Felpita" },
            { id: "id-6", nombre: "Yerba - Amanda" },
            { id: "id-5", nombre: "Yerba - Union" },
            { id: "id-28", nombre: "Tirabuzon - Terrabusi" },
            { id: "id-29", nombre: "Fideos Tubitos - Terrabusi" },
            { id: "id-30", nombre: "Fideos Coditos - Verizzia" },
            { id: "id-31", nombre: "Fideos Tirabuzon Colores - Lucchetti" },
            { id: "id-32", nombre: "Cabello de Angel - Lucchetti" },
            { id: "id-33", nombre: "Spaghetti - Terrabusi" },
            { id: "id-34", nombre: "Educorante - Hileret" },
            { id: "id-35", nombre: "Mate Cocido - Union" },
            { id: "id-36", nombre: "Mate Cocido - Amanda" },
            { id: "id-37", nombre: "Mate Cocido - La Tranquera" },
            { id: "id-38", nombre: "Te - La Virginia" },
            { id: "id-39", nombre: "Yerba de Hierbas Serranas - VerdeFlor" },
            { id: "id-40", nombre: "Yerba de Hierbas Serranas - VerdeFlor" },
            { id: "id-41", nombre: "Yerba - Taragui" },
            { id: "id-42", nombre: "Yerba de Cedron - VerdeFlor" },
            { id: "id-43", nombre: "Salsa de Tomate - Vigente" },
            { id: "id-44", nombre: "Salsa de Tomate - Inca" },
            { id: "id-45", nombre: "Aceite de Girasol - Cocinero" },
            { id: "id-46", nombre: "Aceite de Girasol - Cocinero" }
        ];

        // ID, nombre, marca, cantidad y vencimiento
        const stock = [
            // Productos Re-Stockeados que fueron Aceptados:
            { id: "id-1", nombre: "Arroz Oro", marca: "Gallo", cantidad: "15 x 1kg", vencimiento: "NO ENCONTRADA" },
            { id: "id-2", nombre: "G. de Agua", marca: "La Provinciana", cantidad: "14 x 3", vencimiento: "01/06/2025" },
            { id: "id-19", nombre: "Fideo Codito", marca: "Lucchetti", cantidad: "4 x 500gr", vencimiento: "01/07/2026 (1) - 05/02/2027 (3)" },
            { id: "id-17", nombre: "Fideo Resorte Colores", marca: "Matarazzo", cantidad: "0", vencimiento: "NO ENCONTRADA" },
            { id: "id-4", nombre: "Snack", marca: "Kesitas", cantidad: "6 x 125gr", vencimiento: "26/10/2025" },
            { id: "id-8", nombre: "Lentejas", marca: "Alberio", cantidad: "10 x 400gr", vencimiento: "NO TIENE" },
            { id: "id-20", nombre: "Fideos Tubitos", marca: "Lucchetti", cantidad: "4 x 500gr", vencimiento: "20/02/2027 (2) - 16/01/2027 (2)" },
            { id: "id-21", nombre: "Fideos Tirabuzon", marca: "Lucchetti", cantidad: "4 x 500gr", vencimiento: "13/12/2026 (1) - 20/01/2027 (3)" },
            { id: "id-9", nombre: "Azucar", marca: "Domino", cantidad: "20 x 1kg", vencimiento: "NO TIENE" },
            { id: "id-18", nombre: "Azucar", marca: "F. Canella", cantidad: "18 x 1kg", vencimiento: "NO TIENE" },
            { id: "id-27", nombre: "Cloro", marca: "Ayudin", cantidad: "3 x 450ml", vencimiento: "NO TIENE" },
            { id: "id-24", nombre: "Desinfectante", marca: "CIF", cantidad: "2 x 380ml", vencimiento: "NO TIENE" },
            { id: "id-25", nombre: "Desinfectante", marca: "Lysoform", cantidad: "3 x 490ml", vencimiento: "NO TIENE" },
            { id: "id-26", nombre: "Detergente EXPERT", marca: "CIF", cantidad: "1 x 450ml", vencimiento: "NO TIENE" },
            { id: "id-23", nombre: "Detergente", marca: "CIF", cantidad: "2 x 450ml", vencimiento: "NO TIENE" },
            { id: "id-15", nombre: "Sobre Limonada y Arandanos", marca: "Clight", cantidad: "6 x 20", vencimiento: "20/03/2026" },
            { id: "id-13", nombre: "Sobre Naranja Banana", marca: "TANG", cantidad: "3 x 20", vencimiento: "28/02/2026" },
            { id: "id-14", nombre: "Sobre Pera", marca: "TANG", cantidad: "1 x 19", vencimiento: "04/02/2026" },
            { id: "id-3", nombre: "Mate cocido", marca: "Nobleza Gaucha", cantidad: "10 x 50", vencimiento: "14/02/2027" },
            { id: "id-22", nombre: "Servilleta", marca: "Felpita", cantidad: "2 x 70", vencimiento: "NO TIENE" },
            { id: "id-6", nombre: "Yerba", marca: "Amanda", cantidad: "7 x 500gr", vencimiento: "NO TIENE" },
            { id: "id-5", nombre: "Yerba", marca: "Union", cantidad: "26 x 500gr", vencimiento: "NO TIENE" },
            { id: "id-28", nombre: "Tirabuzon", marca: "Terrabusi", cantidad: "4 x 500gr", vencimiento: "10/02/2026" },
            { id: "id-29", nombre: "Fideos Tubitos", marca: "Terrabusi", cantidad: "6 x 500gr", vencimiento: "30/01/2028 (4) - 10/01/2026 (2)" },
            { id: "id-30", nombre: "Fideos Coditos", marca: "Verizzia", cantidad: "2 x 500gr", vencimiento: "15/02/2026" },
            { id: "id-31", nombre: "Fideos Tirabuzon Colores", marca: "Lucchetti", cantidad: "1 x 500gr", vencimiento: "04/09/2025" },
            { id: "id-32", nombre: "Cabello de Angel", marca: "Lucchetti", cantidad: "1 x 500gr", vencimiento: "21/08/2025" },
            { id: "id-33", nombre: "Spaghetti", marca: "Terrabusi", cantidad: "19 x 500gr", vencimiento: "21/04/2026" },
            { id: "id-34", nombre: "Educorante", marca: "Hileret", cantidad: "4 x 250ml", vencimiento: "01/04/2026" },
            { id: "id-35", nombre: "Mate Cocido", marca: "Union", cantidad: "6 x 50", vencimiento: "01/12/2026" },
            { id: "id-36", nombre: "Mate Cocido", marca: "Amanda", cantidad: "2 x 25", vencimiento: "01/09/2026" },
            { id: "id-37", nombre: "Mate Cocido", marca: "La Tranquera", cantidad: "2 x 50", vencimiento: "NO ENCONTRADA" },
            { id: "id-38", nombre: "Te", marca: "La Virginia", cantidad: "2 x 50", vencimiento: "04/02/2025" },
            { id: "id-39", nombre: "Yerba de Hierbas Serranas", marca: "VerdeFlor", cantidad: "2 x 1kg", vencimiento: "NO TIENE" },
            { id: "id-40", nombre: "Yerba de Hierbas Serranas", marca: "VerdeFlor", cantidad: "4 x 500gr", vencimiento: "NO TIENE" },
            { id: "id-41", nombre: "Yerba", marca: "Taragui", cantidad: "4 x 1kg", vencimiento: "NO TIENE" },
            { id: "id-42", nombre: "Yerba de Cedron", marca: "VerdeFlor", cantidad: "4 x 500gr", vencimiento: "NO TIENE" },
            { id: "id-43", nombre: "Salsa de Tomate", marca: "Vigente", cantidad: "1 x 400gr", vencimiento: "24/03/2026" },
            { id: "id-44", nombre: "Salsa de Tomate", marca: "Inca", cantidad: "8 x 400gr", vencimiento: "27/03/2027" },
            { id: "id-45", nombre: "Aceite de Girasol", marca: "Cocinero", cantidad: "4 x 1,5L", vencimiento: "18/12/2026" },
            { id: "id-46", nombre: "Aceite de Girasol", marca: "Cocinero", cantidad: "3 x 900ml", vencimiento: "17/07/2025 (1) - 21/05/2025 (1) - 13/03/2025 (1)" }
        ]